apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: traceable
        image: iiitbgaurang/traceable_test
        ports:
        - containerPort: 9191
